export const assets = {
  home: {
    hero: "/assets/home/bg-proker-1.jpg",
    lessonWaste: "/assets/home/image-1.png",
    lessonCompost: "/assets/home/image-2.png",
    lessonEco: "/assets/home/image-3.png",
    lessonUses: "/assets/home/image-4.png",
    lessonBusiness: "/assets/home/image-5.png",
    linkArrow: "/assets/home/icon.svg",
    benefitWaste: "/assets/home/frame-1.svg",
    benefitEnvironment: "/assets/home/frame-2.svg",
    benefitValue: "/assets/home/frame.svg",
  },
  waste: {
    hero: "/assets/sampah/bg-proker-2.png",
    organic: "/assets/sampah/image-7.png",
    inorganic: "/assets/sampah/image-8.png",
  },
  compost: {
    hero: "/assets/kompos/image-9.png",
    bucket: "/assets/illustrations/compost-bucket.svg",
    shovel: "/assets/illustrations/hand-trowel.svg",
    greens: "/assets/illustrations/kitchen-scraps.svg",
    browns: "/assets/illustrations/dry-leaves.svg",
    water: "/assets/illustrations/water-cup.svg",
    mature: "/assets/kompos/image-15.png",
    benefitWaste: "/assets/kompos/frame-1.svg",
    benefitPlant: "/assets/kompos/group.svg",
    benefitCycle: "/assets/kompos/frame.svg",
  },
  eco: {
    hero: "/assets/eco/image-9.png",
    benefitPlant: "/assets/eco/image-16.png",
    benefitClean: "/assets/eco/image-17.png",
    benefitEnvironment: "/assets/eco/image-18.png",
    benefitValue: "/assets/eco/image-19.png",
    brownSugar: "/assets/illustrations/palm-sugar.svg",
    produce: "/assets/illustrations/eco-produce.svg",
    water: "/assets/illustrations/water-jug.svg",
    container: "/assets/illustrations/fermentation-container.svg",
    stepContainer: "/assets/eco/image-25.png",
    stepProduce: "/assets/eco/image-26.png",
    stepSugar: "/assets/eco/image-27.png",
    stepWater: "/assets/eco/image-28.png",
    stepMix: "/assets/eco/image-29.png",
    stepFerment: "/assets/eco/image-30.png",
  },
  uses: {
    hero: "/assets/pemanfaatan/hero-pemanfaatan.jpg",
  },
  business: {
    hero: "/assets/usaha/image-37.png",
    productBottle: "/assets/usaha/image-38.png",
    productJar: "/assets/usaha/image-39.png",
    productShowcase: "/assets/usaha/product-showcase-branded.png",
    targetGarden: "/assets/usaha/seedling-solid-11.png",
    targetFarmer: "/assets/usaha/building-wheat-solid-1.png",
    targetHome: "/assets/usaha/house-user-solid-1.png",
    targetShop: "/assets/usaha/money-bill-wheat-solid-1.png",
    digital: "/assets/usaha/image-42.png",
    local: "/assets/usaha/image-43.png",
    packageBottle: "/assets/usaha/image-40.png",
    packageBag: "/assets/usaha/image-41.png",
    businessLogo: "/assets/usaha/logo-nyuburkeun.jpeg",
    labelCompost: "/assets/usaha/label-kompos-revisi.jpeg",
    labelEcoEnzyme: "/assets/usaha/label-eco-enzyme-revisi.jpeg",
    trust: "/assets/usaha/handshake-regular-1.png",
  },
} as const;
